### ISSUE TITLE
Nav bar

### ISSUE THREAD

**Issue by amoskyalo** [savannah-Silica/HTML-CSS-for-begginers#1]
You are expected to come up with a nav bar corresponding to the UI provided

**Comment by Barissa-Imran** [comment]
hi @njambi-muhoro , this task has already been taken: #13  but you can enhance it if you want or go to the next issue and claim it then starting working on it
![sorry-icegif-13](https://user-images.githubusercontent.com/74467681/197015760-6e893863-72f2-423d-a4f5-41f188ecba9e.gif)

**Comment by 254Gits** [comment]
The sign in button has been removed can I add it back
